### Basic build configuration ###
language: java
os: linux
dist: xenial

### Build steps ###
install: skip

script: mvn verify -B

before_deploy: deployment/loadGpgKeys.sh

deploy:
  provider: script
  script: deployment/deploy.sh
  skip_cleanup: true
  on:
    tags: true

### Environment variables ###
env:
  global:
# Sonatype JIRA Username (SONATYPE_USERNAME)
  - secure: SJqbqRkzrCZ9kA1Bj1+4Gnbk7IfRn+IB1U+CIa/7YjIdX3TtxtTW4yABbcHNuYKpDpegMOcqQek2T3gdiLvOvr8au1/KokfPvU2PYe8eUuLzCOVcpe+TFc6gQTRlilLkjahKyPPrBmoT3/5nwibDFglk7mNssY0nevgr4mImNGYeft3NHgEmxX2CIaI8g4wbJfAVvOu6/ZLakex+Ho+mbJTo7A6rv4k68pz//zfeOqYeV5iJ8JWr3V6c8UsA+kuFWySlay+RlkcNjfe8Kog08LpjmIwz+NBsKn+HwbxJUO0OkJq2t39PZHV3b+SbS/msWWbRxWRx38iGScNXf9tLmfVdO7VCOcynX5siFueNJvsVZlqpTJhHADWfoVKMq9Zx+WAtvG+qVvMA1eCu4nk9n3DcSvz9DjGEaUHc2jyiVRZ6x+xKXFI1QTihSLk2aE5Xu0ABYfDSwG/0IVIYN3Ar9CiKjXzTtztQVSH5eQaIHdmxe48ghFoRgQDuBm6KnXK4bBpwvo2+Lff/+tpJE12ub0Bh07YdCgrxU3pzqjAYdCWiXZ5MmvBST3Eff7hdQKAtZvnaCzm+6scQ9R9z+yhHAsTVt0/UWVa+m/SOT6yuJANLMjezPb9Cp8w6Jp68p9hdXZn2hLYIGDvlRf9/Q0D7IO0aGbPH6Lb2f4B3TwOPRSY=
# Sonatype JIRA Password (SONATYPE_PASSWORD)
  - secure: Dwr8Xd1EEsHd8B6X30k3Xqw8vBsIbxHlfpHJQXFrBcMhuZ3QwNHLvIbiVBQ1y5UQ0Zot2Y1KDgk9/3BL3K8cHJesL9YCpkbbFBtG5OWXL8lrP98C34eB/xyKoW4J/kqcVeV/mocR76IYZ+8qjtOQDuWw35rx/KlEhmQJVBXvzxitSAmF6RI7eZd5dOwKKgX8gbc4ABwZoiGfLR6ZH/sI1wX4Tg5pSkCbnxqDg2aNrR0VQisA17KVu17JWCuHLEaqV8EH+WI3vl3i8iB9OqEjVJlp8EgQtkRaYdY1ur8rZTyrPtspqtVrJuafWjqb7ZvFmqDUGJ2iOc1/3iWBBD7bLTGGA4sCX20LgBvx4o3AusEYdo5eZ8x0uS3ffv63DgkinsWuM34iJD/1CS6NmjibmHaM/mULZaB8LQcKxBxrbM6++Oiimpr7h2eZQi20bpIP56/mfxBvW1xH6+kExGFP/RslPDI+i31iDpDDxq5+wNuJXa66t6BvdZidVTixzEWJMO4Nb57AbcZTjr13ruFouWbVLlqBTZpj4Xn8odo3ImiI02wf7O/9ECCyDVOPlD23gO0dhajIgn9nux9DHFfSynrWpfWKTcjcdtZ8sCLMmxtTuxPtJ5tVVHuxgu9+NbANOnitGVkkCm9AzeIld4qXLRCYjDWTz02PHkLaGWA1L3k=
# GPG Key passphrase (GPG_PASSWORD)
  - secure: jgSc1hKo+GcS9wPjPjXrU+TC0U7XlE3+8NrCnQuPkk3kteBv+kJ/yWt5QrDFXow5C04HRvXail3ORJuQ7ARcsg8klKxSvky6ieQjdkVZMurnf/nJkiPcnyH4ezJOo6/VlBJ4AVeYva3LS867vHeWSHYd6ezYxJeezmqRumlKznjtIftlr8DaO8t8ncle18K+/uneSkatr1xE9qELquRNmWMIWwXowouWDM7X4pE0BS00Ks/uPtCh9E3hWnaThmg3JsSBzyBbf6W7vDH4V4/z6QBS82fwL8/94ATfQosIFjshMI+UZzio+Sd048SFxseRPCljRmK6yd8us+dFB4KDqOTvNP3hOCqUmfEQArQpb38PFzGKD/6TVmCbzm5B3nCFdaGCtlMpDRcc87PktiyjYHmLd4WX0GM0u1AmoLBNFX7KjD4gQ2S7ChaKKiNHfeiKlTNKEwK2eM7JoBQKYh9CNFLfTUV4+8LFi6+p9QKXUoiXl7bIsYQsyBH8rMdnbqdKCRHF2w5aZIH/mp+Xnc+wOkKpNxqcmgX7Nf8jKwPbNDbmVqMqcRlWIgJxZGMkdGR4o0E7Ybr/du4ZJpDBScKYhQiol6hB1v0XU6/dNDnxSv0AQvd9ZregNOJi8Kd58afPYUENDgEEkRn/Xf1t7lEYIP4b4cgI2hHgKy953XhWu3I=
